[package]
name = "tiny-image"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.32"
lodepng = "2.4.2"
flate2 = "1.0.7"
imagequant = "3.1.0"